# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5d1df97681eafa02f96655f77e85557aa31a926a22522db81eda19977962a70a9da5c3fc552c24ac8f286184cf018f09a22efc38828cf288aa8ddd03e28a48a

test:
  secret_key_base: e46ea4bccbb9cc675fe027eb1028a15fff76ef9901d6425ff71c0a3c0b5270b5591c8ce03c6aebcd2f3f41714c00a8b1e61b982157a49063adb6ba590d7bb32d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
